image:
  besu:
    tag: 24.6.0

quorumFlags:
  privacy: false
  removeKeysOnDelete: false
  isBootnode: false
  usesBootnodes: true

cluster:
  provider: local
  cloudNativeServices: false
  reclaimPolicy: Retain

node:
  besu:
    envBesuOpts: "-XX:MaxRAMPercentage=60.0 -XX:MinRAMPercentage=60.0 -XX:InitialRAMPercentage=60.0"
    resources:
      cpuLimit: "1500m"
      cpuRequest: "100m"
      memLimit: "4G"
      memRequest: "4G"
    customLabels:
      nodeType: archive
    metrics:
      serviceMonitorEnabled: false
    sync:
      mode: FULL
    rpc:
      maxActiveConnections: 500
      api: '["DEBUG", "ETH", "ADMIN", "NET", "TRACE", "QBFT"]'
    ws:
      api: '["DEBUG", "ETH", "ADMIN", "NET", "TRACE", "QBFT"]'

storage:
  pvcSizeLimit: 2Gi

affinity:
  zone:
  - ap-southeast-2c