image:
  besu:
    tag: 24.6.0

p2p:
  discovery: false

quorumFlags:
  privacy: false
  removeKeysOnDelete: false
  isBootnode: false
  usesBootnodes: false

cluster:
  provider: local
  cloudNativeServices: false
  reclaimPolicy: Retain

node:
  besu:
    envBesuOpts: "-XX:MaxRAMPercentage=50.0 -XX:MinRAMPercentage=30.0 -XX:InitialRAMPercentage=30.0 -XX:InitiatingHeapOccupancyPercent=30 -XX:G1HeapRegionSize=4m -XX:MaxGCPauseMillis=100 -XX:MaxDirectMemorySize=4G -XX:G1ConcRefinementThreads=4 -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics"
    resources:
      cpuLimit: "14500m"
      cpuRequest: "14001m"
      memLimit: "60G"
      memRequest: "60G"
    metrics:
      serviceMonitorEnabled: false
    customLabels:
      nodeType: rpc-6
    rpc:
      maxActiveConnections: 500
      api: '["ETH", "ADMIN", "NET", "QBFT", "TXPOOL"]'
    ws:
      api: '["ETH", "ADMIN", "NET", "QBFT", "TXPOOL"]'

storage:
  pvcSizeLimit: 200Gi
  storageType: SSD

affinity:
  zone:
  - ap-southeast-2c

ingress:
  enabled: false