{{- if (and (eq .Values.node.besu.customLabels.nodeType "rpc") (eq .Release.Name "rpc-1") (.Values.ingress.enabled)) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: "false"
  labels:
    app.kubernetes.io/name: besu-node-rpc
    app.kubernetes.io/component: ingress
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: helm
  name: besu-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: kong
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: besu-node-rpc
            port:
              number: 8545
        path: /
        pathType: Prefix
{{- end }}
