{{- if eq .Values.cluster.provider "azure" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
parameters:
  skuName: Standard_LRS

{{- else if eq .Values.cluster.provider "aws" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: {{ .Values.storage.aws.provisioner }}
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
parameters:
  type: {{ .Values.storage.aws.parameters.type }}
  fsType: {{ .Values.storage.aws.parameters.fsType }}
{{- end }}

