quorumFlags:
  privacy: false
  removeKeysOnDelete: false
  isBootnode: false
  usesBootnodes: true

cluster:
  provider: local
  cloudNativeServices: false
  reclaimPolicy: Retain

node:
  besu:
    envBesuOpts: ""
    metrics:
      serviceMonitorEnabled: false
    sync:
      mode: FAST

storage:
  pvcSizeLimit: 1Gi

affinity:
  zone:
  - ap-southeast-2a