config:
  network:
    id: 9988
    name: Loyalty Testnet
  prometheus:
    enabled: false
    ingressWhitelist:
      enabled: false
    blackbox:
      enabled: false
frontend:
  image:
    tag: "v1.38.2"
  replicaCount: 1
  ingress:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/https-redirect-status-code: "301"
      konghq.com/protocols: "https"
      konghq.com/strip-path: "false"
    hostname: "blockscout.abc-dev.network"
    tls:
      enabled: true
      secretName: frontend-cert-tls
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 2Gi
  env:
    NEXT_PUBLIC_AD_BANNER_PROVIDER: "none"
    NEXT_PUBLIC_AD_TEXT_PROVIDER: "none"
    NEXT_PUBLIC_API_PORT: "443"
    NEXT_PUBLIC_APP_PORT: "443"
    NEXT_PUBLIC_IS_TESTNET: "true"
    NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE: "validation"
blockscout:
  image:
    tag: "7.0.2"
  ingress:
    enabled: true
    className: "kong"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/https-redirect-status-code: "301"
      konghq.com/protocols: "https"
      konghq.com/strip-path: "false"
    hostname: "api-blockscout.abc-dev.network"
    tls:
      enabled: true
      secretName: backend-cert-tls
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 3Gi
  env:
    API_GRAPHQL_ENABLED: "false"
    BLOCKSCOUT_PROTOCOL: "https"
    DATABASE_URL: "postgresql://blockscout:B3SUbl0cksc0ut@rds.in.abc-dev.network:5432/blockscout2"
    DISABLE_EXCHANGE_RATES: "true"
    ECTO_USE_SSL: "false"
    ETHEREUM_JSONRPC_HTTP_INSECURE: "true"
    ETHEREUM_JSONRPC_HTTP_URL: "http://besu-node-archive-1.besu.svc.cluster.local:8545"
    ETHEREUM_JSONRPC_TRACE_URL: "http://besu-node-archive-1.besu.svc.cluster.local:8545"
    ETHEREUM_JSONRPC_VARIANT: "besu"
    ETHEREUM_JSONRPC_WS_URL: "ws://besu-node-archive-1.besu.svc.cluster.local:8546"
    INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: "30"
    INDEXER_CATCHUP_BLOCKS_CONCURRENCY: "10"
    INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true"
    NETWORK: "POA"
    POOL_SIZE_API: 20
    POOL_SIZE: 20
    SECRET_KEY_BASE: "/4uFMwibZ618P3IpkFQXck0Ul9g9kZUKAsP4x3tIzGOLRAE1aOGHsaSP8Ee2LUXP"
    SHOW_PRICE_CHART: "false"
    SHOW_TXS_CHART: "false"
    SUBNETWORK: "POA Sokol"
    TXS_STATS_ENABLED: "false"
stats:
  enabled: false
  image:
    tag: "v2.0.0"
  env:
    STATS__BLOCKSCOUT_DB_URL: "postgresql://blockscout:B3SUbl0cksc0ut@rds.in.abc-dev.network:5432/blockscout"
    STATS__DB_URL: "postgresql://blockscout-stats:AhVu9185K1hliFgp@rds.in.abc-dev.network:5432/blockscout-stats"
    STATS__RUN_MIGRATIONS: "true"