quorumFlags:
  privacy: false
  removeKeysOnDelete: false
  isBootnode: false
  usesBootnodes: true

cluster:
  provider: local
  cloudNativeServices: false
  reclaimPolicy: Retain

node:
  besu:
    metrics:
      serviceMonitorEnabled: false
    account:
      password: 'password'
    customLabels:
      nodeType: rpc-stg
    rpc:
      authenticationEnabled: true
      type: userpass
      credentialsFile: |-
        [Users.admin]
        password = "$2a$10$zMx6JIceFm3vt6Ho.64G7OLylsBlu3An4PxBkAP3IZTd1AiiT3N32"
        permissions = ["*:*"]
        [Users.ozone]
        password = "$2a$10$W3qzcBh7pJheU/649924ceib5x6xXZlpEabZq0.5cDrj8.fUHf2jO"
        permissions = ["eth:*", "txpool:*"]

storage:
  pvcSizeLimit: 1Gi

affinity:
  zone:
  - ap-southeast-2b

ingress:
  enabled: true