image:
  besu:
    tag: 24.6.0

quorumFlags:
  privacy: false
  removeKeysOnDelete: false
  isBootnode: false
  usesBootnodes: true

cluster:
  provider: local
  cloudNativeServices: false
  reclaimPolicy: Retain

node:
  besu:
    metrics:
      serviceMonitorEnabled: false
    customLabels:
      nodeType: rpc
    rpc:
      maxActiveConnections: 240

storage:
  pvcSizeLimit: 1Gi

affinity:
  zone:
  - ap-southeast-2a

ingress:
  enabled: true
  host: besu-rpc.abc-dev.network